
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const WelcomeItem: typeof import("../app/components/WelcomeItem.vue").default
export const IconsIconCommunity: typeof import("../app/components/icons/IconCommunity.vue").default
export const IconsIconDocumentation: typeof import("../app/components/icons/IconDocumentation.vue").default
export const IconsIconEcosystem: typeof import("../app/components/icons/IconEcosystem.vue").default
export const IconsIconSupport: typeof import("../app/components/icons/IconSupport.vue").default
export const IconsIconTooling: typeof import("../app/components/icons/IconTooling.vue").default
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const QAjaxBar: typeof import("quasar").QAjaxBar
export const QAvatar: typeof import("quasar").QAvatar
export const QBadge: typeof import("quasar").QBadge
export const QBanner: typeof import("quasar").QBanner
export const QBar: typeof import("quasar").QBar
export const QBreadcrumbs: typeof import("quasar").QBreadcrumbs
export const QBreadcrumbsEl: typeof import("quasar").QBreadcrumbsEl
export const QBtn: typeof import("quasar").QBtn
export const QBtnDropdown: typeof import("quasar").QBtnDropdown
export const QBtnGroup: typeof import("quasar").QBtnGroup
export const QBtnToggle: typeof import("quasar").QBtnToggle
export const QCard: typeof import("quasar").QCard
export const QCardActions: typeof import("quasar").QCardActions
export const QCardSection: typeof import("quasar").QCardSection
export const QCarousel: typeof import("quasar").QCarousel
export const QCarouselControl: typeof import("quasar").QCarouselControl
export const QCarouselSlide: typeof import("quasar").QCarouselSlide
export const QChatMessage: typeof import("quasar").QChatMessage
export const QCheckbox: typeof import("quasar").QCheckbox
export const QChip: typeof import("quasar").QChip
export const QCircularProgress: typeof import("quasar").QCircularProgress
export const QColor: typeof import("quasar").QColor
export const QDate: typeof import("quasar").QDate
export const QDialog: typeof import("quasar").QDialog
export const QDrawer: typeof import("quasar").QDrawer
export const QEditor: typeof import("quasar").QEditor
export const QExpansionItem: typeof import("quasar").QExpansionItem
export const QFab: typeof import("quasar").QFab
export const QFabAction: typeof import("quasar").QFabAction
export const QField: typeof import("quasar").QField
export const QFile: typeof import("quasar").QFile
export const QFooter: typeof import("quasar").QFooter
export const QForm: typeof import("quasar").QForm
export const QFormChildMixin: typeof import("quasar").QFormChildMixin
export const QHeader: typeof import("quasar").QHeader
export const QIcon: typeof import("quasar").QIcon
export const QImg: typeof import("quasar").QImg
export const QInfiniteScroll: typeof import("quasar").QInfiniteScroll
export const QInnerLoading: typeof import("quasar").QInnerLoading
export const QInput: typeof import("quasar").QInput
export const QIntersection: typeof import("quasar").QIntersection
export const QItem: typeof import("quasar").QItem
export const QItemLabel: typeof import("quasar").QItemLabel
export const QItemSection: typeof import("quasar").QItemSection
export const QList: typeof import("quasar").QList
export const QKnob: typeof import("quasar").QKnob
export const QLayout: typeof import("quasar").QLayout
export const QLinearProgress: typeof import("quasar").QLinearProgress
export const QMarkupTable: typeof import("quasar").QMarkupTable
export const QMenu: typeof import("quasar").QMenu
export const QNoSsr: typeof import("quasar").QNoSsr
export const QOptionGroup: typeof import("quasar").QOptionGroup
export const QPage: typeof import("quasar").QPage
export const QPageContainer: typeof import("quasar").QPageContainer
export const QPageScroller: typeof import("quasar").QPageScroller
export const QPageSticky: typeof import("quasar").QPageSticky
export const QPagination: typeof import("quasar").QPagination
export const QParallax: typeof import("quasar").QParallax
export const QPopupEdit: typeof import("quasar").QPopupEdit
export const QPopupProxy: typeof import("quasar").QPopupProxy
export const QPullToRefresh: typeof import("quasar").QPullToRefresh
export const QRadio: typeof import("quasar").QRadio
export const QRange: typeof import("quasar").QRange
export const QRating: typeof import("quasar").QRating
export const QResizeObserver: typeof import("quasar").QResizeObserver
export const QResponsive: typeof import("quasar").QResponsive
export const QScrollArea: typeof import("quasar").QScrollArea
export const QScrollObserver: typeof import("quasar").QScrollObserver
export const QSelect: typeof import("quasar").QSelect
export const QSeparator: typeof import("quasar").QSeparator
export const QSkeleton: typeof import("quasar").QSkeleton
export const QSlideItem: typeof import("quasar").QSlideItem
export const QSlideTransition: typeof import("quasar").QSlideTransition
export const QSlider: typeof import("quasar").QSlider
export const QSpace: typeof import("quasar").QSpace
export const QSpinner: typeof import("quasar").QSpinner
export const QSpinnerAudio: typeof import("quasar").QSpinnerAudio
export const QSpinnerBall: typeof import("quasar").QSpinnerBall
export const QSpinnerBars: typeof import("quasar").QSpinnerBars
export const QSpinnerBox: typeof import("quasar").QSpinnerBox
export const QSpinnerClock: typeof import("quasar").QSpinnerClock
export const QSpinnerComment: typeof import("quasar").QSpinnerComment
export const QSpinnerCube: typeof import("quasar").QSpinnerCube
export const QSpinnerDots: typeof import("quasar").QSpinnerDots
export const QSpinnerFacebook: typeof import("quasar").QSpinnerFacebook
export const QSpinnerGears: typeof import("quasar").QSpinnerGears
export const QSpinnerGrid: typeof import("quasar").QSpinnerGrid
export const QSpinnerHearts: typeof import("quasar").QSpinnerHearts
export const QSpinnerHourglass: typeof import("quasar").QSpinnerHourglass
export const QSpinnerInfinity: typeof import("quasar").QSpinnerInfinity
export const QSpinnerIos: typeof import("quasar").QSpinnerIos
export const QSpinnerOrbit: typeof import("quasar").QSpinnerOrbit
export const QSpinnerOval: typeof import("quasar").QSpinnerOval
export const QSpinnerPie: typeof import("quasar").QSpinnerPie
export const QSpinnerPuff: typeof import("quasar").QSpinnerPuff
export const QSpinnerRadio: typeof import("quasar").QSpinnerRadio
export const QSpinnerRings: typeof import("quasar").QSpinnerRings
export const QSpinnerTail: typeof import("quasar").QSpinnerTail
export const QSplitter: typeof import("quasar").QSplitter
export const QStep: typeof import("quasar").QStep
export const QStepper: typeof import("quasar").QStepper
export const QStepperNavigation: typeof import("quasar").QStepperNavigation
export const QTabPanel: typeof import("quasar").QTabPanel
export const QTabPanels: typeof import("quasar").QTabPanels
export const QTable: typeof import("quasar").QTable
export const QTd: typeof import("quasar").QTd
export const QTh: typeof import("quasar").QTh
export const QTr: typeof import("quasar").QTr
export const QRouteTab: typeof import("quasar").QRouteTab
export const QTab: typeof import("quasar").QTab
export const QTabs: typeof import("quasar").QTabs
export const QTime: typeof import("quasar").QTime
export const QTimeline: typeof import("quasar").QTimeline
export const QTimelineEntry: typeof import("quasar").QTimelineEntry
export const QToggle: typeof import("quasar").QToggle
export const QToolbar: typeof import("quasar").QToolbar
export const QToolbarTitle: typeof import("quasar").QToolbarTitle
export const QTooltip: typeof import("quasar").QTooltip
export const QTree: typeof import("quasar").QTree
export const QUploader: typeof import("quasar").QUploader
export const QUploaderAddTrigger: typeof import("quasar").QUploaderAddTrigger
export const QVideo: typeof import("quasar").QVideo
export const QVirtualScroll: typeof import("quasar").QVirtualScroll
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyWelcomeItem: LazyComponent<typeof import("../app/components/WelcomeItem.vue").default>
export const LazyIconsIconCommunity: LazyComponent<typeof import("../app/components/icons/IconCommunity.vue").default>
export const LazyIconsIconDocumentation: LazyComponent<typeof import("../app/components/icons/IconDocumentation.vue").default>
export const LazyIconsIconEcosystem: LazyComponent<typeof import("../app/components/icons/IconEcosystem.vue").default>
export const LazyIconsIconSupport: LazyComponent<typeof import("../app/components/icons/IconSupport.vue").default>
export const LazyIconsIconTooling: LazyComponent<typeof import("../app/components/icons/IconTooling.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyQAjaxBar: LazyComponent<typeof import("quasar").QAjaxBar>
export const LazyQAvatar: LazyComponent<typeof import("quasar").QAvatar>
export const LazyQBadge: LazyComponent<typeof import("quasar").QBadge>
export const LazyQBanner: LazyComponent<typeof import("quasar").QBanner>
export const LazyQBar: LazyComponent<typeof import("quasar").QBar>
export const LazyQBreadcrumbs: LazyComponent<typeof import("quasar").QBreadcrumbs>
export const LazyQBreadcrumbsEl: LazyComponent<typeof import("quasar").QBreadcrumbsEl>
export const LazyQBtn: LazyComponent<typeof import("quasar").QBtn>
export const LazyQBtnDropdown: LazyComponent<typeof import("quasar").QBtnDropdown>
export const LazyQBtnGroup: LazyComponent<typeof import("quasar").QBtnGroup>
export const LazyQBtnToggle: LazyComponent<typeof import("quasar").QBtnToggle>
export const LazyQCard: LazyComponent<typeof import("quasar").QCard>
export const LazyQCardActions: LazyComponent<typeof import("quasar").QCardActions>
export const LazyQCardSection: LazyComponent<typeof import("quasar").QCardSection>
export const LazyQCarousel: LazyComponent<typeof import("quasar").QCarousel>
export const LazyQCarouselControl: LazyComponent<typeof import("quasar").QCarouselControl>
export const LazyQCarouselSlide: LazyComponent<typeof import("quasar").QCarouselSlide>
export const LazyQChatMessage: LazyComponent<typeof import("quasar").QChatMessage>
export const LazyQCheckbox: LazyComponent<typeof import("quasar").QCheckbox>
export const LazyQChip: LazyComponent<typeof import("quasar").QChip>
export const LazyQCircularProgress: LazyComponent<typeof import("quasar").QCircularProgress>
export const LazyQColor: LazyComponent<typeof import("quasar").QColor>
export const LazyQDate: LazyComponent<typeof import("quasar").QDate>
export const LazyQDialog: LazyComponent<typeof import("quasar").QDialog>
export const LazyQDrawer: LazyComponent<typeof import("quasar").QDrawer>
export const LazyQEditor: LazyComponent<typeof import("quasar").QEditor>
export const LazyQExpansionItem: LazyComponent<typeof import("quasar").QExpansionItem>
export const LazyQFab: LazyComponent<typeof import("quasar").QFab>
export const LazyQFabAction: LazyComponent<typeof import("quasar").QFabAction>
export const LazyQField: LazyComponent<typeof import("quasar").QField>
export const LazyQFile: LazyComponent<typeof import("quasar").QFile>
export const LazyQFooter: LazyComponent<typeof import("quasar").QFooter>
export const LazyQForm: LazyComponent<typeof import("quasar").QForm>
export const LazyQFormChildMixin: LazyComponent<typeof import("quasar").QFormChildMixin>
export const LazyQHeader: LazyComponent<typeof import("quasar").QHeader>
export const LazyQIcon: LazyComponent<typeof import("quasar").QIcon>
export const LazyQImg: LazyComponent<typeof import("quasar").QImg>
export const LazyQInfiniteScroll: LazyComponent<typeof import("quasar").QInfiniteScroll>
export const LazyQInnerLoading: LazyComponent<typeof import("quasar").QInnerLoading>
export const LazyQInput: LazyComponent<typeof import("quasar").QInput>
export const LazyQIntersection: LazyComponent<typeof import("quasar").QIntersection>
export const LazyQItem: LazyComponent<typeof import("quasar").QItem>
export const LazyQItemLabel: LazyComponent<typeof import("quasar").QItemLabel>
export const LazyQItemSection: LazyComponent<typeof import("quasar").QItemSection>
export const LazyQList: LazyComponent<typeof import("quasar").QList>
export const LazyQKnob: LazyComponent<typeof import("quasar").QKnob>
export const LazyQLayout: LazyComponent<typeof import("quasar").QLayout>
export const LazyQLinearProgress: LazyComponent<typeof import("quasar").QLinearProgress>
export const LazyQMarkupTable: LazyComponent<typeof import("quasar").QMarkupTable>
export const LazyQMenu: LazyComponent<typeof import("quasar").QMenu>
export const LazyQNoSsr: LazyComponent<typeof import("quasar").QNoSsr>
export const LazyQOptionGroup: LazyComponent<typeof import("quasar").QOptionGroup>
export const LazyQPage: LazyComponent<typeof import("quasar").QPage>
export const LazyQPageContainer: LazyComponent<typeof import("quasar").QPageContainer>
export const LazyQPageScroller: LazyComponent<typeof import("quasar").QPageScroller>
export const LazyQPageSticky: LazyComponent<typeof import("quasar").QPageSticky>
export const LazyQPagination: LazyComponent<typeof import("quasar").QPagination>
export const LazyQParallax: LazyComponent<typeof import("quasar").QParallax>
export const LazyQPopupEdit: LazyComponent<typeof import("quasar").QPopupEdit>
export const LazyQPopupProxy: LazyComponent<typeof import("quasar").QPopupProxy>
export const LazyQPullToRefresh: LazyComponent<typeof import("quasar").QPullToRefresh>
export const LazyQRadio: LazyComponent<typeof import("quasar").QRadio>
export const LazyQRange: LazyComponent<typeof import("quasar").QRange>
export const LazyQRating: LazyComponent<typeof import("quasar").QRating>
export const LazyQResizeObserver: LazyComponent<typeof import("quasar").QResizeObserver>
export const LazyQResponsive: LazyComponent<typeof import("quasar").QResponsive>
export const LazyQScrollArea: LazyComponent<typeof import("quasar").QScrollArea>
export const LazyQScrollObserver: LazyComponent<typeof import("quasar").QScrollObserver>
export const LazyQSelect: LazyComponent<typeof import("quasar").QSelect>
export const LazyQSeparator: LazyComponent<typeof import("quasar").QSeparator>
export const LazyQSkeleton: LazyComponent<typeof import("quasar").QSkeleton>
export const LazyQSlideItem: LazyComponent<typeof import("quasar").QSlideItem>
export const LazyQSlideTransition: LazyComponent<typeof import("quasar").QSlideTransition>
export const LazyQSlider: LazyComponent<typeof import("quasar").QSlider>
export const LazyQSpace: LazyComponent<typeof import("quasar").QSpace>
export const LazyQSpinner: LazyComponent<typeof import("quasar").QSpinner>
export const LazyQSpinnerAudio: LazyComponent<typeof import("quasar").QSpinnerAudio>
export const LazyQSpinnerBall: LazyComponent<typeof import("quasar").QSpinnerBall>
export const LazyQSpinnerBars: LazyComponent<typeof import("quasar").QSpinnerBars>
export const LazyQSpinnerBox: LazyComponent<typeof import("quasar").QSpinnerBox>
export const LazyQSpinnerClock: LazyComponent<typeof import("quasar").QSpinnerClock>
export const LazyQSpinnerComment: LazyComponent<typeof import("quasar").QSpinnerComment>
export const LazyQSpinnerCube: LazyComponent<typeof import("quasar").QSpinnerCube>
export const LazyQSpinnerDots: LazyComponent<typeof import("quasar").QSpinnerDots>
export const LazyQSpinnerFacebook: LazyComponent<typeof import("quasar").QSpinnerFacebook>
export const LazyQSpinnerGears: LazyComponent<typeof import("quasar").QSpinnerGears>
export const LazyQSpinnerGrid: LazyComponent<typeof import("quasar").QSpinnerGrid>
export const LazyQSpinnerHearts: LazyComponent<typeof import("quasar").QSpinnerHearts>
export const LazyQSpinnerHourglass: LazyComponent<typeof import("quasar").QSpinnerHourglass>
export const LazyQSpinnerInfinity: LazyComponent<typeof import("quasar").QSpinnerInfinity>
export const LazyQSpinnerIos: LazyComponent<typeof import("quasar").QSpinnerIos>
export const LazyQSpinnerOrbit: LazyComponent<typeof import("quasar").QSpinnerOrbit>
export const LazyQSpinnerOval: LazyComponent<typeof import("quasar").QSpinnerOval>
export const LazyQSpinnerPie: LazyComponent<typeof import("quasar").QSpinnerPie>
export const LazyQSpinnerPuff: LazyComponent<typeof import("quasar").QSpinnerPuff>
export const LazyQSpinnerRadio: LazyComponent<typeof import("quasar").QSpinnerRadio>
export const LazyQSpinnerRings: LazyComponent<typeof import("quasar").QSpinnerRings>
export const LazyQSpinnerTail: LazyComponent<typeof import("quasar").QSpinnerTail>
export const LazyQSplitter: LazyComponent<typeof import("quasar").QSplitter>
export const LazyQStep: LazyComponent<typeof import("quasar").QStep>
export const LazyQStepper: LazyComponent<typeof import("quasar").QStepper>
export const LazyQStepperNavigation: LazyComponent<typeof import("quasar").QStepperNavigation>
export const LazyQTabPanel: LazyComponent<typeof import("quasar").QTabPanel>
export const LazyQTabPanels: LazyComponent<typeof import("quasar").QTabPanels>
export const LazyQTable: LazyComponent<typeof import("quasar").QTable>
export const LazyQTd: LazyComponent<typeof import("quasar").QTd>
export const LazyQTh: LazyComponent<typeof import("quasar").QTh>
export const LazyQTr: LazyComponent<typeof import("quasar").QTr>
export const LazyQRouteTab: LazyComponent<typeof import("quasar").QRouteTab>
export const LazyQTab: LazyComponent<typeof import("quasar").QTab>
export const LazyQTabs: LazyComponent<typeof import("quasar").QTabs>
export const LazyQTime: LazyComponent<typeof import("quasar").QTime>
export const LazyQTimeline: LazyComponent<typeof import("quasar").QTimeline>
export const LazyQTimelineEntry: LazyComponent<typeof import("quasar").QTimelineEntry>
export const LazyQToggle: LazyComponent<typeof import("quasar").QToggle>
export const LazyQToolbar: LazyComponent<typeof import("quasar").QToolbar>
export const LazyQToolbarTitle: LazyComponent<typeof import("quasar").QToolbarTitle>
export const LazyQTooltip: LazyComponent<typeof import("quasar").QTooltip>
export const LazyQTree: LazyComponent<typeof import("quasar").QTree>
export const LazyQUploader: LazyComponent<typeof import("quasar").QUploader>
export const LazyQUploaderAddTrigger: LazyComponent<typeof import("quasar").QUploaderAddTrigger>
export const LazyQVideo: LazyComponent<typeof import("quasar").QVideo>
export const LazyQVirtualScroll: LazyComponent<typeof import("quasar").QVirtualScroll>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
